import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'English' | 'Hindi' | 'Marathi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('English');

  const translations: Record<Language, Record<string, string>> = {
    English: {
      // Onboarding
      'onboarding.skip': 'Skip',
      'onboarding.next': 'Next',
      'onboarding.getStarted': 'Get Started',
      'onboarding.title1': 'Real-time Smart Farming',
      'onboarding.desc1': 'Monitor your farm 24/7 with IoT sensors and get instant updates on crop health, soil conditions, and environmental factors.',
      'onboarding.title2': 'AI-driven Insights & Automation',
      'onboarding.desc2': 'Leverage artificial intelligence to optimize irrigation, predict pest outbreaks, and automate farm operations.',
      'onboarding.title3': 'Grow More With Data',
      'onboarding.desc3': 'Make informed decisions with comprehensive analytics, yield predictions, and actionable insights to maximize productivity.',
      
      // Login/Signup
      'login.title': 'SmartFarm',
      'login.subtitle': 'Your Intelligent Farming Partner',
      'login.login': 'Login',
      'login.signup': 'Sign Up',
      'login.email': 'Email Address',
      'login.emailPlaceholder': 'farmer@smartfarm.com',
      'login.phone': 'Phone Number',
      'login.phonePlaceholder': '+91 98765 43210',
      'login.password': 'Password',
      'login.forgotPassword': 'Forgot Password?',
      'login.enterFarm': 'Enter Your Smart Farm',
      'login.orContinue': 'Or continue with',
      'login.fingerprint': 'Fingerprint Login',
      'login.noAccount': "Don't have an account? ",
      'login.hasAccount': 'Already have an account? ',
      
      // Dashboard
      'dashboard.title': 'Dashboard',
      'dashboard.currentField': 'Current Field',
      'dashboard.todayWeather': "Today's Weather",
      'dashboard.partlyCloudy': 'Partly Cloudy',
      'dashboard.aiRecommendation': 'AI Recommendation',
      'dashboard.aiMessage': 'Soil moisture is dropping. Consider irrigation in 6-8 hours to maintain optimal growth conditions.',
      'dashboard.liveSensorData': 'Live Sensor Data',
      'dashboard.quickActions': 'Quick Actions',
      'dashboard.farmMap': 'Farm Map',
      'dashboard.automation': 'Automation',
      'dashboard.insights': 'Insights',
      'dashboard.home': 'Home',
      'dashboard.analytics': 'Analytics',
      'dashboard.control': 'Control',
      'dashboard.settings': 'Settings',
      
      // Sensors
      'sensor.temperature': 'Temperature',
      'sensor.humidity': 'Humidity',
      'sensor.soilMoisture': 'Soil Moisture',
      'sensor.phLevel': 'pH Level',
      'sensor.lightIntensity': 'Light Intensity',
      
      // Field Map
      'fieldMap.title': 'Field Overview Map',
      'fieldMap.acres': 'acres',
      'fieldMap.myLocation': 'My Location',
      'fieldMap.legend': 'Soil Moisture Legend',
      'fieldMap.optimal': 'Optimal',
      'fieldMap.medium': 'Medium',
      'fieldMap.low': 'Low',
      'fieldMap.sensorStatus': 'Sensor Status',
      'fieldMap.normalOperation': 'Normal Operation',
      'fieldMap.attentionRequired': 'Attention Required',
      
      // Sensor Details
      'sensorDetails.title': 'Sensor Details',
      'sensorDetails.belowOptimal': 'Below Optimal Range',
      'sensorDetails.aiPrediction': 'AI Prediction',
      'sensorDetails.predictionMessage': 'Based on current trends, soil moisture will reach critical levels (<30%) in approximately 18 hours. Immediate irrigation recommended.',
      'sensorDetails.24hours': '24 Hours',
      'sensorDetails.weekly': 'Weekly',
      'sensorDetails.monthly': 'Monthly',
      'sensorDetails.trendAnalysis': 'Trend Analysis',
      'sensorDetails.recommendations': 'Smart Recommendations',
      'sensorDetails.irrigation': 'Irrigation',
      'sensorDetails.irrigationMsg': 'Schedule watering for 2 hours within the next 6-8 hours. Apply 15mm of water evenly across the zone.',
      'sensorDetails.fertilizer': 'Fertilizer',
      'sensorDetails.fertilizerMsg': 'Current moisture level is suitable for nitrogen fertilizer application. Consider applying 50kg/acre.',
      'sensorDetails.pestControl': 'Pest Control',
      'sensorDetails.pestMsg': 'Low moisture combined with high temperatures increases pest risk. Monitor for aphids and spider mites.',
      'sensorDetails.alertThreshold': 'Alert Threshold',
      'sensorDetails.setAlert': 'Set custom alert when soil moisture drops below:',
      'sensorDetails.saveThreshold': 'Save Threshold',
      
      // Alerts
      'alerts.title': 'Alerts & Notifications',
      'alerts.critical': 'Critical',
      'alerts.warning': 'Warning',
      'alerts.safe': 'Safe',
      'alerts.all': 'All',
      'alerts.warnings': 'Warnings',
      'alerts.dismiss': 'Dismiss',
      'alerts.viewDetails': 'View Details',
      'alerts.markAllRead': 'Mark All as Read',
      'alerts.recommendation': 'Recommendation',
      
      // AI Insights
      'insights.title': 'AI Insights',
      'insights.subtitle': 'Predictive analytics and smart recommendations powered by AI',
      'insights.cropGrowth': 'Crop Growth Prediction',
      'insights.cropMessage': 'Based on current conditions, your wheat crop is progressing 12% faster than average seasonal growth.',
      'insights.expectedHarvest': 'Expected Harvest',
      'insights.growthStage': 'Growth Stage',
      'insights.yieldForecast': 'Yield Forecast',
      'insights.projectedProduction': 'Projected monthly production',
      'insights.predictedYield': 'Predicted Total Yield',
      'insights.compared': 'compared to last season',
      'insights.pestRisk': 'Pest/Disease Risk',
      'insights.next7days': 'Next 7 days probability',
      'insights.preventionTip': 'Prevention Tip',
      'insights.preventionMsg': 'Current humidity levels favor aphid activity. Consider applying neem oil spray as a preventive measure.',
      'insights.smartIrrigation': 'Smart Irrigation Schedule',
      'insights.wateringPlan': 'AI-optimized watering plan',
      'insights.today': 'Today',
      'insights.tomorrow': 'Tomorrow',
      'insights.resourceOptimization': 'Energy & Water Optimization',
      'insights.efficiencyScore': 'Current efficiency score',
      'insights.optimized': 'Optimized',
      'insights.efficiencyMsg': 'Your resource usage is above average. Small improvements in irrigation timing could save 12% more water.',
      'insights.waterSaved': 'Water Saved',
      'insights.energySaved': 'Energy Saved',
      'insights.thisMonth': 'This month',
      
      // Automation
      'automation.title': 'Automation Control',
      'automation.active': 'Active',
      'automation.autoMode': 'Auto Mode',
      'automation.devices': 'Devices',
      'automation.quickActions': 'Quick Actions',
      'automation.startAll': 'Start All',
      'automation.stopAll': 'Stop All',
      'automation.waterPump': 'Water Pump',
      'automation.irrigationValve': 'Irrigation Valve',
      'automation.fertilizerSprayer': 'Fertilizer Sprayer',
      'automation.greenhouseFan': 'Greenhouse Fan',
      'automation.growLights': 'Grow Lights',
      'automation.schedule': 'Schedule',
      'automation.timerSchedule': 'Timer Schedule',
      'automation.addDevice': 'Add New Device',
      
      // Analytics
      'analytics.title': 'Analytics & History',
      'analytics.week': 'Week',
      'analytics.month': 'Month',
      'analytics.year': 'Year',
      'analytics.growth': 'Growth',
      'analytics.avgYield': 'Avg Yield',
      'analytics.period': 'Period',
      'analytics.multiField': 'Multi-Field Soil Moisture Comparison',
      'analytics.tempPattern': 'Daily Temperature Pattern',
      'analytics.peakTemp': 'Peak Temperature',
      'analytics.average': 'Average',
      'analytics.heatmap': 'Soil Moisture Heatmap - North Field A',
      'analytics.distribution': 'Distribution across field zones',
      'analytics.exportData': 'Export Data',
      'analytics.exportDesc': 'Download detailed reports and analytics data',
      'analytics.weeklyReport': 'Weekly Report',
      'analytics.pdfFormat': 'PDF format with charts',
      'analytics.rawData': 'Raw Data Export',
      'analytics.csvFormat': 'CSV format for analysis',
      'analytics.customReport': 'Custom Report',
      'analytics.selectRange': 'Select date range & metrics',
      
      // Settings
      'settings.title': 'Settings',
      'settings.language': 'Language',
      'settings.theme': 'Theme',
      'settings.lightMode': 'Light Mode',
      'settings.darkMode': 'Dark Mode',
      'settings.natureGreen': 'Nature Green',
      'settings.appSettings': 'App Settings',
      'settings.notifications': 'Notifications',
      'settings.notificationsDesc': 'Push alerts for critical events',
      'settings.offlineMode': 'Offline Mode',
      'settings.offlineModeDesc': 'Save data locally when offline',
      'settings.deviceManagement': 'Device Management',
      'settings.deviceManagementDesc': 'Manage connected IoT devices',
      'settings.appPermissions': 'App Permissions',
      'settings.appPermissionsDesc': 'Location, camera, storage',
      'settings.helpSupport': 'Help & Support',
      'settings.helpSupportDesc': 'FAQ, tutorials, contact us',
      'settings.privacyPolicy': 'Privacy Policy',
      'settings.privacyPolicyDesc': 'How we handle your data',
      'settings.logout': 'Log Out',
    },
    Hindi: {
      // Onboarding
      'onboarding.skip': 'छोड़ें',
      'onboarding.next': 'आगे',
      'onboarding.getStarted': 'शुरू करें',
      'onboarding.title1': 'रीयल-टाइम स्मार्ट फार्मिंग',
      'onboarding.desc1': 'IoT सेंसर के साथ अपने खेत की 24/7 निगरानी करें और फसल स्वास्थ्य, मिट्टी की स्थिति और पर्यावरणीय कारकों पर तत्काल अपडेट प्राप्त करें।',
      'onboarding.title2': 'AI-संचालित अंतर्दृष्टि और स्वचालन',
      'onboarding.desc2': 'सिंचाई को अनुकूलित करने, कीट प्रकोप की भविष्यवाणी करने और खेती के कार्यों को स्वचालित करने के लिए कृत्रिम बुद्धिमत्ता का लाभ उठाएं।',
      'onboarding.title3': 'डेटा के साथ अधिक उगाएं',
      'onboarding.desc3': 'उत्पादकता को अधिकतम करने के लिए व्यापक विश्लेषण, उपज पूर्वानुमान और कार्रवाई योग्य अंतर्दृष्टि के साथ सूचित निर्णय लें।',
      
      // Login/Signup
      'login.title': 'स्मार्टफार्म',
      'login.subtitle': 'आपका बुद्धिमान कृषि साथी',
      'login.login': 'लॉगिन',
      'login.signup': 'साइन अप',
      'login.email': 'ईमेल पता',
      'login.emailPlaceholder': 'farmer@smartfarm.com',
      'login.phone': 'फ़ोन नंबर',
      'login.phonePlaceholder': '+91 98765 43210',
      'login.password': 'पासवर्ड',
      'login.forgotPassword': 'पासवर्ड भूल गए?',
      'login.enterFarm': 'अपने स्मार्ट फार्म में प्रवेश करें',
      'login.orContinue': 'या जारी रखें',
      'login.fingerprint': 'फिंगरप्रिंट लॉगिन',
      'login.noAccount': 'खाता नहीं है? ',
      'login.hasAccount': 'पहले से खाता है? ',
      
      // Dashboard
      'dashboard.title': 'डैशबोर्ड',
      'dashboard.currentField': 'वर्तमान खेत',
      'dashboard.todayWeather': 'आज का मौसम',
      'dashboard.partlyCloudy': 'आंशिक बादल',
      'dashboard.aiRecommendation': 'AI सिफारिश',
      'dashboard.aiMessage': 'मिट्टी की नमी कम हो रही है। इष्टतम वृद्धि स्थितियों को बनाए रखने के लिए 6-8 घंटों में सिंचाई पर विचार करें।',
      'dashboard.liveSensorData': 'लाइव सेंसर डेटा',
      'dashboard.quickActions': 'त्वरित क्रियाएं',
      'dashboard.farmMap': 'खेत का नक्शा',
      'dashboard.automation': 'स्वचालन',
      'dashboard.insights': 'अंतर्दृष्टि',
      'dashboard.home': 'होम',
      'dashboard.analytics': 'विश्लेषण',
      'dashboard.control': 'नियंत्रण',
      'dashboard.settings': 'सेटिंग्स',
      
      // Sensors
      'sensor.temperature': 'तापमान',
      'sensor.humidity': 'आर्द्रता',
      'sensor.soilMoisture': 'मिट्टी की नमी',
      'sensor.phLevel': 'pH स्तर',
      'sensor.lightIntensity': 'प्रकाश तीव्रता',
      
      // Field Map
      'fieldMap.title': 'खेत अवलोकन मानचित्र',
      'fieldMap.acres': 'एकड़',
      'fieldMap.myLocation': 'मेरा स्थान',
      'fieldMap.legend': 'मिट्टी नमी किंवदंती',
      'fieldMap.optimal': 'इष्टतम (45-65%)',
      'fieldMap.medium': 'मध्यम (35-45%)',
      'fieldMap.low': 'कम (<35%)',
      'fieldMap.sensorStatus': 'सेंसर स्थिति',
      'fieldMap.normalOperation': 'सामान्य संचालन',
      'fieldMap.attentionRequired': 'ध्यान आवश्यक',
      
      // Sensor Details
      'sensorDetails.title': 'सेंसर विवरण',
      'sensorDetails.belowOptimal': 'इष्टतम सीमा से नीचे',
      'sensorDetails.aiPrediction': 'AI पूर्वानुमान',
      'sensorDetails.predictionMessage': 'वर्तमान रुझानों के आधार पर, मिट्टी की नमी लगभग 18 घंटों में महत्वपूर्ण स्तर (<30%) तक पहुंच जाएगी। तत्काल सिंचाई की सिफारिश की जाती है।',
      'sensorDetails.24hours': '24 घंटे',
      'sensorDetails.weekly': 'साप्ताहिक',
      'sensorDetails.monthly': 'मासिक',
      'sensorDetails.trendAnalysis': 'रुझान विश्लेषण',
      'sensorDetails.recommendations': 'स्मार्ट सिफारिशें',
      'sensorDetails.irrigation': 'सिंचाई',
      'sensorDetails.irrigationMsg': 'अगले 6-8 घंटों के भीतर 2 घंटे के लिए पानी देने का समय निर्धारित करें। पूरे क्षेत्र में समान रूप से 15mm पानी लगाएं।',
      'sensorDetails.fertilizer': 'उर्वरक',
      'sensorDetails.fertilizerMsg': 'वर्तमान नमी स्तर नाइट्रोजन उर्वरक अनुप्रयोग के लिए उपयुक्त है। 50kg/एकड़ लगाने पर विचार करें।',
      'sensorDetails.pestControl': 'कीट नियंत्रण',
      'sensorDetails.pestMsg': 'उच्च तापमान के साथ कम नमी कीट जोखिम को बढ़ाती है। एफिड्स और स्पाइडर माइट्स की निगरानी करें।',
      'sensorDetails.alertThreshold': 'चेतावनी सीमा',
      'sensorDetails.setAlert': 'मिट्टी की नमी कम होने पर कस्टम अलर्ट सेट करें:',
      'sensorDetails.saveThreshold': 'सीमा सहेजें',
      
      // Alerts
      'alerts.title': 'चेतावनी और सूचनाएं',
      'alerts.critical': 'गंभीर',
      'alerts.warning': 'चेतावनी',
      'alerts.safe': 'सुरक्षित',
      'alerts.all': 'सभी',
      'alerts.warnings': 'चेतावनियां',
      'alerts.dismiss': 'खारिज करें',
      'alerts.viewDetails': 'विवरण देखें',
      'alerts.markAllRead': 'सभी को पढ़ा हुआ चिह्नित करें',
      'alerts.recommendation': 'सिफारिश',
      
      // AI Insights
      'insights.title': 'AI अंतर्दृष्टि',
      'insights.subtitle': 'AI द्वारा संचालित भविष्यवाणी विश्लेषण और स्मार्ट सिफारिशें',
      'insights.cropGrowth': 'फसल वृद्धि पूर्वानुमान',
      'insights.cropMessage': 'वर्तमान परिस्थितियों के आधार पर, आपकी गेहूं की फसल औसत मौसमी वृद्धि से 12% तेजी से आगे बढ़ रही है।',
      'insights.expectedHarvest': 'अपेक्षित कटाई',
      'insights.growthStage': 'वृद्धि चरण',
      'insights.yieldForecast': 'उपज पूर्वानुमान',
      'insights.projectedProduction': 'अनुमानित मासिक उत्पादन',
      'insights.predictedYield': 'अनुमानित कुल उपज',
      'insights.compared': 'पिछले सीजन की तुलना में',
      'insights.pestRisk': 'कीट/रोग जोखिम',
      'insights.next7days': 'अगले 7 दिनों की संभावना',
      'insights.preventionTip': 'रोकथाम टिप',
      'insights.preventionMsg': 'वर्तमान आर्द्रता स्तर एफिड गतिविधि के पक्ष में हैं। निवारक उपाय के रूप में नीम तेल स्प्रे लगाने पर विचार करें।',
      'insights.smartIrrigation': 'स्मार्ट सिंचाई अनुसूची',
      'insights.wateringPlan': 'AI-अनुकूलित पानी देने की योजना',
      'insights.today': 'आज',
      'insights.tomorrow': 'कल',
      'insights.resourceOptimization': 'ऊर्जा और पानी अनुकूलन',
      'insights.efficiencyScore': 'वर्तमान दक्षता स्कोर',
      'insights.optimized': 'अनुकूलित',
      'insights.efficiencyMsg': 'आपका संसाधन उपयोग औसत से ऊपर है। सिंचाई समय में छोटे सुधार 12% अधिक पानी बचा सकते हैं।',
      'insights.waterSaved': 'पानी बचाया',
      'insights.energySaved': 'ऊर्जा बचाई',
      'insights.thisMonth': 'इस महीने',
      
      // Automation
      'automation.title': 'स्वचालन नियंत्रण',
      'automation.active': 'सक्रिय',
      'automation.autoMode': 'ऑटो मोड',
      'automation.devices': 'उपकरण',
      'automation.quickActions': 'त्वरित क्रियाएं',
      'automation.startAll': 'सभी शुरू करें',
      'automation.stopAll': 'सभी बंद करें',
      'automation.waterPump': 'पानी का पंप',
      'automation.irrigationValve': 'सिंचाई वाल्व',
      'automation.fertilizerSprayer': 'उर्वरक स्प्रेयर',
      'automation.greenhouseFan': 'ग्रीनहाउस पंखा',
      'automation.growLights': 'ग्रो लाइट्स',
      'automation.schedule': 'अनुसूची',
      'automation.timerSchedule': 'टाइमर अनुसूची',
      'automation.addDevice': 'नया उपकरण जोड़ें',
      
      // Analytics
      'analytics.title': 'विश्लेषण और इतिहास',
      'analytics.week': 'सप्ताह',
      'analytics.month': 'महीना',
      'analytics.year': 'वर्ष',
      'analytics.growth': 'वृद्धि',
      'analytics.avgYield': 'औसत उपज',
      'analytics.period': 'अवधि',
      'analytics.multiField': 'बहु-क्षेत्र मिट्टी नमी तुलना',
      'analytics.tempPattern': 'दैनिक तापमान पैटर्न',
      'analytics.peakTemp': 'शिखर तापमान',
      'analytics.average': 'औसत',
      'analytics.heatmap': 'मिट्टी नमी हीटमैप - उत्तर क्षेत्र A',
      'analytics.distribution': 'क्षेत्र क्षेत्रों में वितरण',
      'analytics.exportData': 'डेटा निर्यात करें',
      'analytics.exportDesc': 'विस्तृत रिपोर्ट और विश्लेषण डेटा डाउनलोड करें',
      'analytics.weeklyReport': 'साप्ताहिक रिपोर्ट',
      'analytics.pdfFormat': 'चार्ट के साथ PDF प्रारूप',
      'analytics.rawData': 'कच्चा डेटा निर्यात',
      'analytics.csvFormat': 'विश्लेषण के लिए CSV प्रारूप',
      'analytics.customReport': 'कस्टम रिपोर्ट',
      'analytics.selectRange': 'तिथि सीमा और मेट्रिक्स चुनें',
      
      // Settings
      'settings.title': 'सेटिंग्स',
      'settings.language': 'भाषा',
      'settings.theme': 'थीम',
      'settings.lightMode': 'लाइट मोड',
      'settings.darkMode': 'डार्क मोड',
      'settings.natureGreen': 'प्रकृति हरा',
      'settings.appSettings': 'ऐप सेटिंग्स',
      'settings.notifications': 'सूचनाएं',
      'settings.notificationsDesc': 'महत्वपूर्ण घटनाओं के लिए पुश अलर्ट',
      'settings.offlineMode': 'ऑफ़लाइन मोड',
      'settings.offlineModeDesc': 'ऑफ़लाइन होने पर डेटा स्थानीय रूप से सहेजें',
      'settings.deviceManagement': 'डिवाइस प्रबंधन',
      'settings.deviceManagementDesc': 'कनेक्टेड IoT उपकरणों का प्रबंधन करें',
      'settings.appPermissions': 'ऐप अनुमतियां',
      'settings.appPermissionsDesc': 'स्थान, कैमरा, भंडारण',
      'settings.helpSupport': 'सहायता और समर्थन',
      'settings.helpSupportDesc': 'FAQ, ट्यूटोरियल, हमसे संपर्क करें',
      'settings.privacyPolicy': 'गोपनीयता नीति',
      'settings.privacyPolicyDesc': 'हम आपके डेटा को कैसे संभालते हैं',
      'settings.logout': 'लॉग आउट',
    },
    Marathi: {
      // Onboarding
      'onboarding.skip': 'वगळा',
      'onboarding.next': 'पुढे',
      'onboarding.getStarted': 'सुरू करा',
      'onboarding.title1': 'रिअल-टाइम स्मार्ट शेती',
      'onboarding.desc1': 'IoT सेन्सर सह तुमच्या शेताचे 24/7 निरीक्षण करा आणि पीक आरोग्य, माती स्थिती आणि पर्यावरणीय घटकांवर त्वरित अद्यतने मिळवा.',
      'onboarding.title2': 'AI-चालित अंतर्दृष्टी आणि स्वयंचलन',
      'onboarding.desc2': 'सिंचन अनुकूलित करण्यासाठी, कीटक प्रादुर्भावाचा अंदाज लावण्यासाठी आणि शेती कार्ये स्वयंचलित करण्यासाठी कृत्रिम बुद्धिमत्तेचा लाभ घ्या.',
      'onboarding.title3': 'डेटासह अधिक पिकवा',
      'onboarding.desc3': 'उत्पादकता वाढवण्यासाठी सर्वसमावेशक विश्लेषण, उत्पन्न अंदाज आणि कार्यवाही करण्यायोग्य अंतर्दृष्टीसह माहितीपूर्ण निर्णय घ्या.',
      
      // Login/Signup
      'login.title': 'स्मार्टफार्म',
      'login.subtitle': 'तुमचा बुद्धिमान शेती साथीदार',
      'login.login': 'लॉगिन',
      'login.signup': 'साइन अप',
      'login.email': 'ईमेल पत्ता',
      'login.emailPlaceholder': 'farmer@smartfarm.com',
      'login.phone': 'फोन नंबर',
      'login.phonePlaceholder': '+91 98765 43210',
      'login.password': 'पासवर्ड',
      'login.forgotPassword': 'पासवर्ड विसरलात?',
      'login.enterFarm': 'तुमच्या स्मार्ट फार्ममध्ये प्रवेश करा',
      'login.orContinue': 'किंवा सुरू ठेवा',
      'login.fingerprint': 'फिंगरप्रिंट लॉगिन',
      'login.noAccount': 'खाते नाही? ',
      'login.hasAccount': 'आधीपासूनच खाते आहे? ',
      
      // Dashboard
      'dashboard.title': 'डॅशबोर्ड',
      'dashboard.currentField': 'सध्याचे शेत',
      'dashboard.todayWeather': 'आजचे हवामान',
      'dashboard.partlyCloudy': 'अंशतः ढगाळ',
      'dashboard.aiRecommendation': 'AI शिफारस',
      'dashboard.aiMessage': 'मातीची ओलावा कमी होत आहे. इष्टतम वाढीची परिस्थिती राखण्यासाठी 6-8 तासांत सिंचनावर विचार करा.',
      'dashboard.liveSensorData': 'लाइव्ह सेन्सर डेटा',
      'dashboard.quickActions': 'द्रुत क्रिया',
      'dashboard.farmMap': 'शेत नकाशा',
      'dashboard.automation': 'स्वयंचलन',
      'dashboard.insights': 'अंतर्दृष्टी',
      'dashboard.home': 'होम',
      'dashboard.analytics': 'विश्लेषण',
      'dashboard.control': 'नियंत्रण',
      'dashboard.settings': 'सेटिंग्ज',
      
      // Sensors
      'sensor.temperature': 'तापमान',
      'sensor.humidity': 'आर्द्रता',
      'sensor.soilMoisture': 'मातीची ओलावा',
      'sensor.phLevel': 'pH पातळी',
      'sensor.lightIntensity': 'प्रकाश तीव्रता',
      
      // Field Map
      'fieldMap.title': 'शेत विहंगावलोकन नकाशा',
      'fieldMap.acres': 'एकर',
      'fieldMap.myLocation': 'माझे स्थान',
      'fieldMap.legend': 'माती ओलावा दिग्दर्शक',
      'fieldMap.optimal': 'इष्टतम (45-65%)',
      'fieldMap.medium': 'मध्यम (35-45%)',
      'fieldMap.low': 'कमी (<35%)',
      'fieldMap.sensorStatus': 'सेन्सर स्थिती',
      'fieldMap.normalOperation': 'सामान्य ऑपरेशन',
      'fieldMap.attentionRequired': 'लक्ष आवश्यक',
      
      // Sensor Details
      'sensorDetails.title': 'सेन्सर तपशील',
      'sensorDetails.belowOptimal': 'इष्टतम श्रेणीच्या खाली',
      'sensorDetails.aiPrediction': 'AI अंदाज',
      'sensorDetails.predictionMessage': 'सध्याच्या ट्रेंडच्या आधारावर, मातीची ओलावा अंदाजे 18 तासांत गंभीर पातळीवर (<30%) पोहोचेल. त्वरित सिंचनाची शिफारस केली जाते.',
      'sensorDetails.24hours': '24 तास',
      'sensorDetails.weekly': 'साप्ताहिक',
      'sensorDetails.monthly': 'मासिक',
      'sensorDetails.trendAnalysis': 'ट्रेंड विश्लेषण',
      'sensorDetails.recommendations': 'स्मार्ट शिफारसी',
      'sensorDetails.irrigation': 'सिंचन',
      'sensorDetails.irrigationMsg': 'पुढील 6-8 तासांत 2 तासांसाठी पाणी देण्याचे शेड्यूल करा. संपूर्ण झोनमध्ये समान रीतीने 15mm पाणी लावा.',
      'sensorDetails.fertilizer': 'खत',
      'sensorDetails.fertilizerMsg': 'सध्याची ओलावा पातळी नायट्रोजन खत वापरासाठी योग्य आहे. 50kg/एकर लावण्याचा विचार करा.',
      'sensorDetails.pestControl': 'कीटक नियंत्रण',
      'sensorDetails.pestMsg': 'उच्च तापमानासह कमी ओलावा कीटक धोका वाढवतो. एफिड्स आणि स्पायडर माइट्सचे निरीक्षण करा.',
      'sensorDetails.alertThreshold': 'सूचना मर्यादा',
      'sensorDetails.setAlert': 'मातीची ओलावा कमी झाल्यावर सानुकूल सूचना सेट करा:',
      'sensorDetails.saveThreshold': 'मर्यादा जतन करा',
      
      // Alerts
      'alerts.title': 'सूचना आणि अधिसूचना',
      'alerts.critical': 'गंभीर',
      'alerts.warning': 'चेतावणी',
      'alerts.safe': 'सुरक्षित',
      'alerts.all': 'सर्व',
      'alerts.warnings': 'चेतावण्या',
      'alerts.dismiss': 'फेटाळा',
      'alerts.viewDetails': 'तपशील पहा',
      'alerts.markAllRead': 'सर्व वाचलेले चिन्हांकित करा',
      'alerts.recommendation': 'शिफारस',
      
      // AI Insights
      'insights.title': 'AI अंतर्दृष्टी',
      'insights.subtitle': 'AI द्वारे समर्थित भविष्यसूचक विश्लेषण आणि स्मार्ट शिफारसी',
      'insights.cropGrowth': 'पीक वाढ अंदाज',
      'insights.cropMessage': 'सध्याच्या परिस्थितीच्या आधारावर, तुमचे गहू पीक सरासरी हंगामी वाढीपेक्षा 12% वेगाने प्रगती करत आहे.',
      'insights.expectedHarvest': 'अपेक्षित कापणी',
      'insights.growthStage': 'वाढ टप्पा',
      'insights.yieldForecast': 'उत्पन्न अंदाज',
      'insights.projectedProduction': 'अंदाजे मासिक उत्पादन',
      'insights.predictedYield': 'अंदाजे एकूण उत्पन्न',
      'insights.compared': 'मागील हंगामाच्या तुलनेत',
      'insights.pestRisk': 'कीटक/रोग धोका',
      'insights.next7days': 'पुढील 7 दिवसांची शक्यता',
      'insights.preventionTip': 'प्रतिबंध टीप',
      'insights.preventionMsg': 'सध्याची आर्द्रता पातळी एफिड क्रियाकलापांना अनुकूल आहे. प्रतिबंधात्मक उपाय म्हणून कडुनिंब तेल फवारणी लावण्याचा विचार करा.',
      'insights.smartIrrigation': 'स्मार्ट सिंचन वेळापत्रक',
      'insights.wateringPlan': 'AI-अनुकूलित पाणी देण्याची योजना',
      'insights.today': 'आज',
      'insights.tomorrow': 'उद्या',
      'insights.resourceOptimization': 'ऊर्जा आणि पाणी अनुकूलन',
      'insights.efficiencyScore': 'सध्याचा कार्यक्षमता स्कोअर',
      'insights.optimized': 'अनुकूलित',
      'insights.efficiencyMsg': 'तुमचा संसाधन वापर सरासरीपेक्षा जास्त आहे. सिंचन वेळेत लहान सुधारणा 12% अधिक पाणी वाचवू शकतात.',
      'insights.waterSaved': 'पाणी वाचवले',
      'insights.energySaved': 'ऊर्जा वाचवली',
      'insights.thisMonth': 'या महिन्यात',
      
      // Automation
      'automation.title': 'स्वयंचलन नियंत्रण',
      'automation.active': 'सक्रिय',
      'automation.autoMode': 'ऑटो मोड',
      'automation.devices': 'उपकरणे',
      'automation.quickActions': 'द्रुत क्रिया',
      'automation.startAll': 'सर्व सुरू करा',
      'automation.stopAll': 'सर्व थांबवा',
      'automation.waterPump': 'पाण्याचा पंप',
      'automation.irrigationValve': 'सिंचन व्हॉल्व्ह',
      'automation.fertilizerSprayer': 'खत फवारणी',
      'automation.greenhouseFan': 'ग्रीनहाउस पंखा',
      'automation.growLights': 'ग्रो लाइट्स',
      'automation.schedule': 'वेळापत्रक',
      'automation.timerSchedule': 'टाइमर वेळापत्रक',
      'automation.addDevice': 'नवीन उपकरण जोडा',
      
      // Analytics
      'analytics.title': 'विश्लेषण आणि इतिहास',
      'analytics.week': 'आठवडा',
      'analytics.month': 'महिना',
      'analytics.year': 'वर्ष',
      'analytics.growth': 'वाढ',
      'analytics.avgYield': 'सरासरी उत्पन्न',
      'analytics.period': 'कालावधी',
      'analytics.multiField': 'बहु-क्षेत्र माती ओलावा तुलना',
      'analytics.tempPattern': 'दैनिक तापमान पॅटर्न',
      'analytics.peakTemp': 'शिखर तापमान',
      'analytics.average': 'सरासरी',
      'analytics.heatmap': 'माती ओलावा हीटमॅप - उत्तर क्षेत्र A',
      'analytics.distribution': 'क्षेत्र झोनमध्ये वितरण',
      'analytics.exportData': 'डेटा निर्यात करा',
      'analytics.exportDesc': 'तपशीलवार अहवाल आणि विश्लेषण डेटा डाउनलोड करा',
      'analytics.weeklyReport': 'साप्ताहिक अहवाल',
      'analytics.pdfFormat': 'चार्टसह PDF स्वरूप',
      'analytics.rawData': 'कच्चा डेटा निर्यात',
      'analytics.csvFormat': 'विश्लेषणासाठी CSV स्वरूप',
      'analytics.customReport': 'सानुकूल अहवाल',
      'analytics.selectRange': 'तारीख श्रेणी आणि मेट्रिक्स निवडा',
      
      // Settings
      'settings.title': 'सेटिंग्ज',
      'settings.language': 'भाषा',
      'settings.theme': 'थीम',
      'settings.lightMode': 'लाइट मोड',
      'settings.darkMode': 'डार्क मोड',
      'settings.natureGreen': 'निसर्ग हिरवा',
      'settings.appSettings': 'अॅप सेटिंग्ज',
      'settings.notifications': 'सूचना',
      'settings.notificationsDesc': 'गंभीर घटनांसाठी पुश सूचना',
      'settings.offlineMode': 'ऑफलाइन मोड',
      'settings.offlineModeDesc': 'ऑफलाइन असताना डेटा स्थानिक पातळीवर जतन करा',
      'settings.deviceManagement': 'डिव्हाइस व्यवस्थापन',
      'settings.deviceManagementDesc': 'कनेक्ट केलेल्या IoT उपकरणांचे व्यवस्थापन करा',
      'settings.appPermissions': 'अॅप परवानग्या',
      'settings.appPermissionsDesc': 'स्थान, कॅमेरा, स्टोरेज',
      'settings.helpSupport': 'मदत आणि समर्थन',
      'settings.helpSupportDesc': 'FAQ, ट्यूटोरियल, आमच्याशी संपर्क साधा',
      'settings.privacyPolicy': 'गोपनीयता धोरण',
      'settings.privacyPolicyDesc': 'आम्ही तुमचा डेटा कसा हाताळतो',
      'settings.logout': 'लॉग आउट',
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
